name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update
    - name: upgrade
      run: sudo apt upgrade -y
    - name: clean
      run: sudo apt clean
    - name: install_dependencies
      run: sudo apt install git wget nano gh tmate build-essential gcc-aarch64-linux-gnu g++-x86-64-linux-gnu binutils-x86-64-linux-gnu crossbuild-essential-arm64 make m4 automake autoconf libtool autotools-dev cmake  bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils zstd cpio -y
    - name: static_dependencies
      run: cd /usr/local; mkdir devs; wget https://github.com/wong-fi-hung/termux-miner_build-depends/releases/download/v1.0.0/amd64_deps.tar.xz; tar -xvf amd64_deps.tar.xz; mv amd64_deps/* devs; rm -rvf amd64_deps
    - name: clone_gitsource
      run: cd && git clone https://github.com/wong-fi-hung/termux-miner && cd termux-miner
    - name: generate_configure_script
      run: autoreconf -i
    - name: configuring
      run: ./configure --with-crypto --with-curl CC=gcc CXX=g++ CFLAGS="-Ofast -fuse-linker-plugin -ftree-loop-if-convert -march=x86-64+generic -mcpu=x86-64+generic -mtune=generic" CXXFLAGS="$CFLAGS" CPPFLAGS="$CFLAGS -I. -I/usr/local/devs/include" LDFLAGS="-L/usr/local/devs/lib -static" LIBS="-lcurl -lcrypto -lssl"
    - name: Make
      run: make -j4
    - name: strip
      run: strip -s cpuminer
    - name: mktargz
      run: mkdir termux-miner-v3.0.0; cp cpuminer cpuminer-conf.json termux-miner-v3.0.0; tar -Jcvf termux-miner-v3.0.0_amd64.tar.xz termux-miner-v3.0.0
    - name: run_tmate_cmd
      run: tmate -F
